const game = () => {
	let pScore = 0;
	let guessed = [];

	let spaceWords = [
		'antimatter',
		'black hole',
		'asteroid',
		'red giant',
		'earth',
		'gamma ray',
		'gravity',
		'meteorite',
		'neptune',
		'pulsar',
		'quasar',
		'solar rain',
		'supernova'
	];

	// Computer randomely selects a word from the space words array
	const randomWord = spaceWords[Math.floor(Math.random() * spaceWords.length + 1)];

	// Start the Game
	const startGame = () => {
		const playbtn = document.getElementById('intro-btn');
		const introScreen = document.querySelector('.jumbotron');
		const gameScreen = document.querySelector('.game');

		playbtn.addEventListener('click', () => {
			introScreen.classList.add('fadeOut');
			gameScreen.classList.add('fadeIn');
		});
	};

	const printButtons = () => {
		let alphabet = [
			'a',
			'b',
			'c',
			'd',
			'e',
			'f',
			'g',
			'h',
			'i',
			'j',
			'k',
			'l',
			'm',
			'n',
			'o',
			'p',
			'q',
			'r',
			's',
			't',
			'u',
			'v',
			'w',
			'x',
			'y',
			'z'
		];

		for (i = 0; i < alphabet.length; i++) {
			// let name = document.createTextNode(alphabet[i]);
			let btn = document.createElement('button');
			btn.type = 'button';
			btn.className = 'btn btn-light';
			let name = document.createTextNode(alphabet[i]);
			btn.appendChild(name);
			btn.id = btn.innerHTML;
			document.getElementById('alphabet').appendChild(btn);
			checkGuess(btn, randomWord);
		}
	};

	const checkGuess = (letter, randomWord) => {
		letter.addEventListener('click', () => {
			console.log(letter.id);
			guessed.indexOf(letter.id) === -1 ? guessed.push(letter.id) : null;
			// Returns - 1 if the item is not found, so if letter clicked not found in guessed array already, push it to the array
			document.getElementById(letter.id).setAttribute('disabled', true);
			// console.log(guessed);

			// if
		});
	};

	// Create blanks on the screen for word to be guessed
	// how it works:
	// using random word generated by computer, function splits it by each letter and then runs through each of them
	// it then goes to the guessed array
	// if letter of random word exists in guest array, then place the letter there- to fill spaces where same letter appears more than once
	// if not, then it leaves a blank

	function guessedWord(randomWord) {
		console.log(randomWord);
		wordStatus = randomWord.split('').map((letter) => (guessed.indexOf(letter) >= 0 ? letter : ' _ ')).join('');

		document.getElementById('blanks').innerHTML = wordStatus;
	}

	startGame();
	printButtons();
	guessedWord(randomWord);

	// draw different parts of hangman when guess incorrectly
	// functions divided by parts

	const drawHangman = () => {
		var canvas = document.getElementById('myCanvas');
		var ctx = canvas.getContext('2d');
	};
};

game();
